#   Copyright 2019 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ param.ci_config.pipeline_namespace }}-pv
  labels:
    type: local
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  storageClassName: epoch-tekton-pipeline-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/data/epoch/workspaces/workspace-{{ workspace_id }}/{{ param.ci_config.pipeline_namespace }}-pv
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ param.node }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-pvc
  namespace: {{ param.ci_config.pipeline_namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: epoch-tekton-pipeline-storage
  volumeMode: Filesystem
  volumeName: {{ param.ci_config.pipeline_namespace }}-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ param.ci_config.pipeline_namespace }}-sonarqube-pv
  labels:
    type: local
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  storageClassName: epoch-tekton-pipeline-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/data/epoch/workspaces/workspace-{{ workspace_id }}/{{ param.ci_config.pipeline_namespace }}-sonarqube-pv
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ param.node }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-sonarqube-pvc
  namespace: {{ param.ci_config.pipeline_namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: epoch-tekton-pipeline-storage
  volumeMode: Filesystem
  volumeName: {{ param.ci_config.pipeline_namespace }}-sonarqube-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ param.ci_config.pipeline_namespace }}-sonarqube-db-pv
  labels:
    type: local
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  storageClassName: epoch-tekton-pipeline-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/data/epoch/workspace-{{ workspace_id }}/{{ param.ci_config.pipeline_namespace }}-sonarqube-db-pv
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ param.node }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-sonarqube-db-pvc
  namespace: {{ param.ci_config.pipeline_namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: epoch-tekton-pipeline-storage
  volumeMode: Filesystem
  volumeName: {{ param.ci_config.pipeline_namespace }}-sonarqube-db-pv
