#   Copyright 2019 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentication-infra-conf
  namespace: exastro-platform-authentication-infra
data:
  api_authc_infra.conf: |
    TZ='Asia/Tokyo'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-infra-api
  namespace: exastro-platform-authentication-infra
spec:
  selector:
    matchLabels:
      name: authentication-infra-api
  replicas: 1
  template:
    metadata:
      labels:
        name: authentication-infra-api
    spec:
      volumes:
      - name: authentication-infra-conf
        configMap:
          name: authentication-infra-conf
      - name: gateway-conf-template
        configMap:
          name: gateway-conf-template
      - name: nodeport-template
        configMap:
          name: nodeport-template
      - name: gateway-httpd-conf
        persistentVolumeClaim:
          claimName: exastro-authentication-infra-httpd-conf
      containers:
      - name: authentication-infra-api
        image: exastro/authentication-infra-api:0.3.0_20211206_1700
        env:
        - name: CONFIG_API_AUTHC_INFRA_PATH
          value: "/etc/exastro-authentication-infra/authentication-infra-api/api_authc_infra.conf"
        - name: FLASK_ENV
          value: "development"
        - name: API_AUTHC_INFRA_PORT
          value: "8000"
        - name: PYTHONIOENCODING
          value: utf-8
        - name: EXASTRO_HTTP_PROXY
          valueFrom:
            configMapKeyRef:
              name: proxy-setting-config
              key: HTTP_PROXY
        - name: EXASTRO_HTTPS_PROXY
          valueFrom:
            configMapKeyRef:
              name: proxy-setting-config
              key: HTTPS_PROXY
        - name: EXASTRO_NO_PROXY
          value: ""
        - name: CONF_TEMPLATE_PATH
          value: "/app/exastro-authentication-infra/authentication-infra-conf-templates"
        - name: NODEPORT_TEMPLATE_PATH
          value: "/app/exastro-authentication-infra/authentication-infra-nodeport-templates"
        - name: EXASTRO_KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: exastro-platform-authentication-infra-secret
              key: KEYCLOAK_USER
        - name: EXASTRO_KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: exastro-platform-authentication-infra-secret
              key: KEYCLOAK_PASSWORD
        - name: EXASTRO_KEYCLOAK_MASTER_REALM
          value: "master"
        - name: GATEWAY_CRYPTO_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: exastro-platform-authentication-infra-secret
              key: GATEWAY_CRYPTO_PASSPHRASE
        - name: EXASTRO_KEYCLOAK_HOST
          valueFrom:
            configMapKeyRef:
              name: exastro-platform-authentication-infra-env
              key: EXASTRO_KEYCLOAK_HOST
        - name: EXASTRO_KEYCLOAK_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: exastro-platform-authentication-infra-env
              key: EXASTRO_KEYCLOAK_PROTOCOL
        - name: EXASTRO_KEYCLOAK_PORT
          valueFrom:
            configMapKeyRef:
              name: exastro-platform-authentication-infra-env
              key: EXASTRO_KEYCLOAK_PORT
        - name: API_KEYCLOAK_HOST
          value: "keycloak.exastro-platform-authentication-infra.svc"
        - name: API_KEYCLOAK_PROTOCOL
          value: "http"
        - name: API_KEYCLOAK_PORT
          value: "8080"
        - name: GATEWAY_HTTPD_CONF_CM_NAME
          value: "gateway-httpd-conf"
        - name: EXASTRO_AUTHC_NAMESPACE
          value: "exastro-platform-authentication-infra"
        - name: GATEWAY_HTTPD_DEPLOY_NAME
          value: "gateway-httpd"
        - name: GATEWAY_HTTPD_CONF_PATH
          value: "/var/exastro-authentication-infra/httpd-conf"
        volumeMounts:
        - name: authentication-infra-conf
          mountPath: /etc/exastro-authentication-infra/authentication-infra-api
        - name: gateway-conf-template
          mountPath: /app/exastro-authentication-infra/authentication-infra-conf-templates
        - name: nodeport-template
          mountPath: /app/exastro-authentication-infra/authentication-infra-nodeport-templates
        - name: gateway-httpd-conf
          mountPath: /var/exastro-authentication-infra/httpd-conf

---

apiVersion: v1
kind: Service
metadata:
  name: authentication-infra-api
  labels:
    name: authentication-infra-api
  namespace: exastro-platform-authentication-infra
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    name: authentication-infra-api
