#   Copyright 2021 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: epoch-control-inside-gitlab-conf
  namespace: epoch-system
data:
  api_inside_gitlab.conf: |
    TZ='Asia/Tokyo'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epoch-control-inside-gitlab-api
  namespace: epoch-system
spec:
  selector:
    matchLabels:
      name: epoch-control-inside-gitlab-api
  replicas: 1
  template:
    metadata:
      labels:
        name: epoch-control-inside-gitlab-api
    spec:
      volumes:
      - name: epoch-control-inside-gitlab-conf
        configMap:
          name: epoch-control-inside-gitlab-conf
      containers:
      - name: epoch-control-inside-gitlab-api
        image: exastro/epoch-control-inside-gitlab-api:0.1.5_20210930_1420
        env:
        - name: CONFIG_API_INSIDE_GITLAB_PATH
          value: "/etc/epoch/epochControlInsideGitLabApi/api_inside_gitlab.conf"
        - name: FLASK_ENV
          value: "development"
        - name: API_INSIDE_GITLAB_PORT
          value: "8000"
        - name: PYTHONIOENCODING
          value: utf-8
        - name: EPOCH_WEBHOOK_PORT
          value: "30804"
        - name: EPOCH_HTTP_PROXY
          valueFrom:
            configMapKeyRef:
              name: proxy-setting-config
              key: HTTP_PROXY
        - name: EPOCH_HTTPS_PROXY
          valueFrom:
            configMapKeyRef:
              name: proxy-setting-config
              key: HTTPS_PROXY
        - name: EPOCH_NO_PROXY
          value: ""
        volumeMounts:
        - name: epoch-control-inside-gitlab-conf
          mountPath: /etc/epoch/epochControlInsideGitLabApi
---
apiVersion: v1
kind: Service
metadata:
  name: epoch-control-inside-gitlab-api
  labels:
    name: epoch-control-inside-gitlab-api
  namespace: epoch-system
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    name: epoch-control-inside-gitlab-api
