#   Copyright 2021 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: epoch-control-workspace-conf
  namespace: epoch-system
data:
  api_workspace.conf: |
    TZ='Asia/Tokyo'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epoch-control-workspace-api
  namespace: epoch-system
spec:
  selector:
    matchLabels:
      name: epoch-control-workspace-api
  replicas: 1
  template:
    metadata:
      labels:
        name: epoch-control-workspace-api
    spec:
      volumes:
      - name: epoch-control-workspace-conf
        configMap:
          name: epoch-control-workspace-conf
      containers:
      - name: epoch-control-workspace-api
        image: exastro/epoch-control-workspace-api:1.1.0_20220630_1100
        env:
        - name: CONFIG_API_WORKSPACE_PATH
          value: "/etc/epoch/epochControlWorkspaceApi/api_workspace.conf"
        - name: FLASK_ENV
          value: "production"
        - name: API_WORKSPACE_PORT
          value: "8000"
        - name: PYTHONIOENCODING
          value: utf-8
        - name: EPOCH_RS_WORKSPACE_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: epoch-control-api-config
              key: RS_WORKSPACE_PROTOCOL
        - name: EPOCH_RS_WORKSPACE_HOST
          valueFrom:
            configMapKeyRef:
              name: epoch-control-api-config
              key: RS_WORKSPACE_HOST
        - name: EPOCH_RS_WORKSPACE_PORT
          valueFrom:
            configMapKeyRef:
              name: epoch-control-api-config
              key: RS_WORKSPACE_PORT
        volumeMounts:
        - name: epoch-control-workspace-conf
          mountPath: /etc/epoch/epochControlWorkspaceApi
---
apiVersion: v1
kind: Service
metadata:
  name: epoch-control-workspace-api
  labels:
    name: epoch-control-workspace-api
  namespace: epoch-system
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    name: epoch-control-workspace-api
