#   Copyright 2021 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: epoch-control-github-conf
  namespace: epoch-system
data:
  api_github.conf: |
    TZ='Asia/Tokyo'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epoch-control-github-api
  namespace: epoch-system
spec:
  selector:
    matchLabels:
      name: epoch-control-github-api
  replicas: 1
  template:
    metadata:
      labels:
        name: epoch-control-github-api
    spec:
      volumes:
      - name: epoch-control-github-conf
        configMap:
          name: epoch-control-github-conf
      containers:
      - name: epoch-control-github-api
        image: exastro/epoch-control-github-api:0.3.1_20220207_1100
        env:
        - name: HTTP_PROXY
          valueFrom:
            configMapKeyRef:
              name: proxy-setting-config
              key: HTTP_PROXY
        - name: HTTPS_PROXY
          valueFrom:
            configMapKeyRef:
              name: proxy-setting-config
              key: HTTPS_PROXY
        - name: NO_PROXY
          value: localhost,127.0.0.1,10.96.0.1,kurbernetes.default.svc,kurbernetes.default.svc.cluster.local
        - name: CONFIG_API_GITHUB_PATH
          value: "/etc/epoch/epochControlGitHubApi/api_github.conf"
        - name: FLASK_ENV
          value: "development"
        - name: API_GITHUB_PORT
          value: "8000"
        - name: PYTHONIOENCODING
          value: utf-8
        - name: EPOCH_WEBHOOK_PORT
          valueFrom:
            configMapKeyRef:
              name: epoch-control-api-config
              key: WEBHOOK_PORT
        volumeMounts:
        - name: epoch-control-github-conf
          mountPath: /etc/epoch/epochControlGitHubApi
---
apiVersion: v1
kind: Service
metadata:
  name: epoch-control-github-api
  labels:
    name: epoch-control-github-api
  namespace: epoch-system
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    name: epoch-control-github-api
