#   Copyright 2019 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: epoch-control-api-config
  namespace: epoch-system
data:
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  NO_PROXY: "localhost,127.0.0.1"
  ARGOCD_NO_PROXY: "localhost,127.0.0.1,kurbernetes.default.svc,kurbernetes.default.svc.cluster.local,10.96.0.1,argocd-server,argocd-dex-server,argocd-redis,argocd-repo-server,argocd-server-metrics"
  ARGOCD_HOST: "argocd-server.epoch-workspace.svc"
  ITA_HOST: "it-automation.epoch-workspace.svc"
  ITA_PORT: "8084"
  ITA_WORKER_HOST: "ita-worker.epoch-workspace.svc"
  WEBHOOK_PORT: "30443"
  RS_WORKSPACE_PROTOCOL: "http"
  RS_WORKSPACE_HOST: "epoch-rs-workspace-api"
  RS_WORKSPACE_PORT: "8000"
