apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-httpd-conf
  namespace: exastro-platform-authentication-infra
data:
  gateway-httpd.conf: |
    #

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-httpd
  namespace: exastro-platform-authentication-infra
spec:
  selector:
    matchLabels:
      name: gateway-httpd
  replicas: 1
  template:
    metadata:
      labels:
        name: gateway-httpd
    spec:
      volumes:
      - name: gateway-httpd-conf
        configMap:
          name: gateway-httpd-conf
      containers:
      - name: gateway-httpd
        image: exastro/gateway-httpd:0.1.5_20211026_1420
        volumeMounts:
        - name: gateway-httpd-conf
          mountPath: /etc/httpd/conf.d/exastroSettings/

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-httpd
  labels:
    app: gateway-httpd
  namespace: exastro-platform-authentication-infra
spec:
  ports:
  - name: http
    port: 31181
    targetPort: 31181
    nodePort: 31181
  selector:
    name: gateway-httpd
  type: NodePort
