#!/bin/bash
#   Copyright 2021 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


# Processing to output the log from the beginning
echo ""
sleep 10

cat <<EOF
#
# exastro epoch setting utility : host setting
#
EOF

if [ $# -ne 1 ]; then
    echo "Usage : `basename $0` [hostname or IPaddress]"
    echo "ERROR : Check the parameters and try again"
    exit 1
fi

echo "[INFO] Wait for Running setting tools pod"
while true; do
    STATUS_SETTING_POD=$(kubectl get pod -n epoch-system --selector name=epoch-setting-tools -o jsonpath='{.items[0].status.phase}')
    if [ $? -eq 0 -a "${STATUS_SETTING_POD}" = "Running" ]; then
        break;
    fi
    sleep 5;
done

echo "[INFO] Call set-host command"
kubectl exec -i deploy/epoch-setting-tools -n epoch-system -- bash /scripts/set-host.sh $1

echo "[INFO] Call set-host-gitlab command"
cat <<EOF | sed -e "s/#HOST#/$1/g" | kubectl apply -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: set-host-gitlab
  namespace: epoch-system
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: set-host-gitlab
    spec:
      restartPolicy: Never
      containers:
      - name: set-host-gitlab
        image: exastro/epoch-kube-command:0.1.5_20211026_1600
        command: ["sh", "-c"]
        args:
          - |
            kubectl exec -i deploy/epoch-setting-tools -n epoch-system -- bash /scripts/set-host-gitlab.sh #HOST# &&
            kubectl delete job/set-host-gitlab -n epoch-system
EOF


echo "**** ${BASENAME} completed successfully ****"
exit 0
